# Generated by Django 4.0.3 on 2022-04-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothingStore', '0002_rename_quantity_orderitem_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
