# Generated by Django 4.0.3 on 2022-04-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothingStore', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pricePerDay',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
