# Generated by Django 4.0.3 on 2022-04-16 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothingStore', '0004_alter_product_priceperday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='username',
        ),
    ]
